# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAPwcjNhQVR5ZZRZiMuHVOJ0Cx6bknXn
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import pandas as pd
import json
from groq import Groq

app = Flask(__name__)
CORS(app)

# =========================
# CONFIG
# =========================
import os
PASSWORD = "PRUEBASUNA"

#EXCEL_FILE = "consolidadosuna.xlsx"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
EXCEL_FILE = os.path.join(BASE_DIR, "consolidadosuna.xlsx")
SHEET_NAME = "Consolidado_29.05"
SHEET_DIC = "DIC"

# =========================
# LOAD DATA
# =========================

def load_data():
    df = pd.read_excel(EXCEL_FILE, sheet_name=SHEET_NAME)

    df.columns = (
        df.columns
        .str.replace("\n", " ", regex=False)
        .str.replace("  ", " ")
        .str.strip()
    )

    df["FECHA DE CORTE"] = pd.to_datetime(df["FECHA DE CORTE"])

    return df


def load_dic():
    dic = pd.read_excel(EXCEL_FILE, sheet_name=SHEET_DIC)

    dic.columns = (
        dic.columns
        .str.replace("\n", " ", regex=False)
        .str.replace("  ", " ")
        .str.strip()
    )

    return dic


df = load_data()
df_dic = load_dic()

# =========================
# LOGIN
# =========================

@app.route("/login", methods=["POST"])
def login():

    data = request.json

    password = data.get("password")

    if password != PASSWORD:
        return jsonify({
            "success": False,
            "error": "Contraseña incorrecta"
        })

    return jsonify({
        "success": True
    })


# =========================
# CHAT
# =========================

@app.route("/chat", methods=["POST"])
def chat():

    data = request.json

    api_key = data.get("api_key")
    intendencia = data.get("intendencia")
    categorias = data.get("categorias", [])
    pregunta = data.get("pregunta")

    if not api_key:
        return jsonify({
            "respuesta": "Falta API Key"
        })

    # =========================
    # CLIENT GROQ
    # =========================

    client = Groq(api_key=api_key)

    # =========================
    # GENERAL SIEMPRE
    # =========================

    categorias_finales = ["GENERAL"] + categorias

    # =========================
    # MAPEO COLUMNAS
    # =========================

    indices_columnas = (
        df_dic[
            df_dic["CATEGORIA"].isin(categorias_finales)
        ]["COLUMNA"]
        .dropna()
        .astype(int)
        .unique()
        .tolist()
    )

    columnas = [
        df.columns[i]
        for i in indices_columnas
        if i < len(df.columns)
    ]

    # =========================
    # FILTRO PRINCIPAL
    # =========================

    df_filtrado = df[
        df["INTENDENCIA"] == intendencia
    ]

    data = df_filtrado[columnas].to_dict(orient="records")

    print("DF_DIC SHAPE:", df_dic.shape)
    print("CATEGORIAS:", categorias_finales)
    print("COLUMNAS:", columnas)
    print("DATA LEN:", len(data))

    # =========================
    # PROMPT
    # =========================

    prompt = f"""
Eres un analista de datos SUNAFIL.

INTENDENCIA: {intendencia}

Usa únicamente estos datos:

{json.dumps(data, default=str)}

Pregunta:
{pregunta}

Reglas:
- No inventes información
- Si no hay datos, dilo claramente
- Respuesta máxima 5 líneas
"""

    # =========================
    # GROQ
    # =========================

    try:

        resp = client.chat.completions.create(
            model="openai/gpt-oss-120b",
            messages=[
                {
                    "role": "system",
                    "content": "Responde de forma ejecutiva, breve y basada solo en datos."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0
        )

        respuesta = resp.choices[0].message.content

    except Exception as e:

        return jsonify({
            "success": False,
            "respuesta": f"Error Groq: {str(e)}"
        })

    return jsonify({
        "success": True,
        "respuesta": respuesta
    })


# =========================
# RUN
# =========================

if __name__ == "__main__":
    import os

    port = int(os.environ.get("PORT", 10000))

    app.run(host="0.0.0.0", port=port)
